package com.digitalchocolate.androidrollergapp;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class drawable {
        public static final int i1 = 0x7f020000;
    }
}
